version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - mongodb_network

networks:
  mongodb_network:
    external: true
